### ISSUE TITLE
$SERVD_ASSETS_ENVIRONMENT env var isn't being used unless explicitly set in plugin settings

### ISSUE THREAD

**Issue by jsunsawyer** [servdhost/craft-asset-storage#11]
This is inconsistent with how the defaults work when setting up asset volumes, and made me think that env var wasn't working properly.

**Comment by mattgrayisok** [comment]
Fixed in [2.0.0-beta.1](https://github.com/servdhost/craft-asset-storage/releases/tag/v2.0.0-beta.1)

The suggested env var is now defaulted if nothing is set
