### ISSUE TITLE
URLs for non-images are malformed, results in 404

### ISSUE THREAD

**Issue by johndwells** [servdhost/craft-asset-storage#3]
When I do {{ asset.url }} for a non-image (including an SVG), the URL it returns look like this:

https://my-handle-staging.cl-us-east-1.servd.dev/my-cp-trigger/$SERVD_BASE_URL/my-handle/staging/filename.ext

I have so far tried SVGs and PDFs. Both result in the malformed URL.

As you can surmise from the URL, we have configured the volume's base public URL to be, as expected, `$SERVD_BASE_URL`.

Perhaps relevant, this does not happen in my local environment. Only staging. I have not yet tried in production.

Craft 3.4.30, Asset Storage 1.1.0.

**Comment by mattgrayisok** [comment]
Hey, I would expect the above if the asset volume's base URL has been set to the `$SERVD_BASE_URL` env var, as you mentioned, but the environment variable doesn't exist. Has `SERVD_BASE_URL` been added to the list of env vars in the Servd dashboard?

Cheers

**Comment by johndwells** [comment]
Yep, that was it. I mistakenly thought those were all populated automatically. Thanks!
