### ISSUE TITLE
Error on Asset Upload

### ISSUE THREAD

**Issue by joshparylak** [servdhost/craft-asset-storage#31]
When Uploading an asset, an error displays in a javascript alert:
`Upload failed. The Error Message was: "Getting unknown property: servd\AssetStorage\Volume::path"`

The asset however did actually upload and is now available to select. All assets properly display and are viewable both in the Craft CP and in the S3 instance itself when I look in Cyberduck.

Plugin Version 2.4.8, Craft CMS version Craft CMS 3.7.18.2

**Comment by mattgrayisok** [comment]
Hey @joshparylak! Thanks for reporting this. I'm struggling to recreate on this side. However my feeling is that there's another plugin or module installed which is trying to do something with uploaded assets by hooking into the asset upload event.

The fact that the error is trying to access the `path` property on the `Volume` object suggests to me that whatever it is, it's assuming that all Volumes are Local Filesystem volumes (which are the only volume types that have a `path` property).

If you're able to find a stack trace for the error in any associated log files that should have a reference to the PHP file which is causing this and point us in the right direction!

**Comment by joshparylak** [comment]
@mattgrayisok Thanks for the reply here. It looks like the culprit was another plugin. I had already identified that it wouldn't work with non-local filesystems but had only sidestepped it, not removed it yet. Removing it has cleared this problem. Thanks for pointing me in the right direction.

**Comment by mattgrayisok** [comment]
No problem, glad it was a simple one to diagnose 👍
