### ISSUE TITLE
Transformed Images CDN Url

### ISSUE THREAD

**Issue by JJimmyFlynn** [servdhost/craft-asset-storage#33]
Apologies if this is working as intended, but I'm wondering if images output by twig should ever reference the `cdn2.assets-servd.host` url. Our images always reference the transformer url `optimise2.assets-servd.host` even when images have (presumably) already been transformed. I'm able to navigate directly to an image url on the CDN, so it seems they're making it there.

We're using Imager and have set everything up according to the docs.

A live example can be found here: https://prod.hellobonfire.com/

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/2218753/141878773-8ed25fab-5cdf-4a4c-b6db-6ad0ef299412.png">

**Comment by mattgrayisok** [comment]
Hey! The plugin will always use the optimise2 subdomain for anything that it thinks is an optimisable image (jpg, gif, png etc) but will use the cdn2 subdomain for everything else (pdfs, svgs etc).

The differences between the two:
- optimise2 will run the image through the transform and optimisation layer and apply transforms as per the query params you will have seen in the URLs. It then stores a cached copy of the result before passing the final file through a caching CDN
- cdn2 just pulls the original file directly through the caching CDN

The plugin itself isn't able to determine which files have been pre-optimised so it just tries to optimise everything, but if you don't want that to happen, there's a global disable transfroms switch in the plugin settings. Once that's flipped everything will be pulled via cdn2:

`Disable Asset Platform image transforms / optimisations`

Feel free to experiment - it's easy to flip that back on again if required.

**Comment by JJimmyFlynn** [comment]
Got it, thanks for the explanation Matt!
