### ISSUE TITLE
`./craft servd-asset-storage/local/pull-assets` is a bit too eager to delete assets

### ISSUE THREAD

**Issue by mgburns** [servdhost/craft-asset-storage#50]
We're using the following CLI commands in our project:

```
./craft servd-asset-storage/local/pull-database --from=staging--interactive=0
./craft servd-asset-storage/local/pull-assets --from=staging --interactive=0
```

We've noticed that running the latter frequently deletes local assets that it shouldn't. Namely, assets that are referenced in the database pull / assets that are present when we visit the Servd staging site. We can work around it by using `--skipDelete`, but flagging it just in case others are hitting it as well!

**Comment by mattgrayisok** [comment]
I believe this is fixed (finally) in v3.4.4 which includes a fix for a doubled up directory separator in the logic for syncing files
