### ISSUE TITLE
Static Cache purge entry URL button missing in v3.0

### ISSUE THREAD

**Issue by chrismlusk** [servdhost/craft-asset-storage#52]
Craft v4 [removed control panel template hooks](https://craftcms.com/docs/4.x/extend/updating-plugins.html#template-hooks), which were used [to add the `static-cache-clear.twig` template](https://github.com/servdhost/craft-asset-storage/blob/master/src/StaticCache/StaticCache.php#L477-L508) to entry edit pages. This feature has proved useful for clients. Is this on your upgrade roadmap?

**Comment by mattgrayisok** [comment]
Hey! Thanks for reporting. I didn't realise this had actually changed so I'll get an update added in to resolve.

**Comment by mattgrayisok** [comment]
Fixed and released in v3.0.5
