### ISSUE TITLE
Maintain an up-to-date changelog

### ISSUE THREAD

**Issue by johndwells** [servdhost/craft-asset-storage#6]
It would be great if the changelog could be updated to document changes that come with each release. These changes would then appear in the CP when we're alerted to updates:

https://craftcms.com/docs/3.x/extend/changelogs-and-updates.html

**Comment by mattgrayisok** [comment]
Can I hire you to keep tabs on the quality of my releases more generally? 😅

Updated for the latest version and I'll make sure to make a habit of it!

**Comment by johndwells** [comment]
🎊
