### ISSUE TITLE
`purgeUrls()` fails on index URL

### ISSUE THREAD

**Issue by raray** [servdhost/craft-asset-storage#77]
The code in `master` does not match what I see installed with version `3.5.10` in composer so I'm not sure how to link to the line. What I see for lines 19-21 in `craft/vendor/servd/craft-asset-storage/src/StaticCache/Ledge.php` is this:

```
foreach ($urls as $url) {
    $urlParts = parse_url($url);
    if($urlParts['path'] == '' || $urlParts['path'] == '/') {
```

That `if` statement will error if the URL passed has no path, such as `https://mysite.com` since `path` will not be set as an index. The line should be:

```
if(empty($urlParts['path']) || $urlParts['path'] == '/') {
```

**Comment by mattgrayisok** [comment]
Just released an update to fix this for all Craft versions 👍
